### ISSUE TITLE
Compilation having an error

### ISSUE THREAD

**Issue by TY-cc** [osu-crypto/BaRK-OPRF#10]
Thanks for providing the source code.
I found an error  when compilating the code.  as follow

./bOPRFlib/Network/BtSocket.h:75:3: error: invalid use of template-name ‘boost::asio::strand’ without an argument list
   boost::asio::strand mSendStrand, mRecvStrand;
compilation terminated due to -Wfatal-errors.
makefile:119: recipe for target 'Release/./bOPRFlib/Network/BtEndpoint.o' failed
make: *** [Release/./bOPRFlib/Network/BtEndpoint.o] Error 1

How  can i do?

**Comment by ladnir** [comment]
looks like you are using a newer version of boost than is expected. Consider using libPSI which contains this protocol.

**Comment by TY-cc** [comment]
thanks for  your reply. but i am not really understand your means. what is the libPSI? is  it  included the bOPRFlib of your source?

**Comment by ladnir** [comment]
https://github.com/osu-crypto/libPSI/tree/master/libPSI/PSI/Kkrt for the psi protocol. 

 https://github.com/osu-crypto/libOTe/tree/master/libOTe/NChooseOne/Kkrt for the oprf protocol.

**Comment by TY-cc** [comment]
thanks！ i was a little busy the other days. i will learn these contents
