### ISSUE TITLE
An Issue about the Code

### ISSUE THREAD

**Issue by MySylviaa** [osu-crypto/BaRK-OPRF#13]
Hi! Thank you for offering the source code!
I'm studying PSI and OPRF these days and I have read the paper about BaRK-OPRF. I have a problem about the program, so can you tell me the reason and the way to solve it? 

![issue](https://user-images.githubusercontent.com/96474221/157416964-89fcc924-361f-4569-80ca-254dc9fba818.png)

**Comment by ladnir** [comment]
no longer maintained, use libPSI which has kkrt (barkoprf).
