### ISSUE TITLE
the Data Type “block”

### ISSUE THREAD

**Issue by MySylviaa** [osu-crypto/BaRK-OPRF#15]
Hello! I'm trying to modify the file main.cpp for inputting my own datasets. However, I find the input datatype in BopTest() to be "block". So what does the type "block" refer to? And how to change other data types( for example, string) to "block"? Thank you!

**Comment by ladnir** [comment]
libPSI has this functionality and protocol. a block is just a 16-byte element. You would hash the string to get a block.
