### ISSUE TITLE
Data size of 2 to the 24th power does not work

### ISSUE THREAD

**Issue by cyy521xx** [osu-crypto/BaRK-OPRF#16]
Data size of 2 to the 24th power does not work. How can I solve this problem? Thank you very much for your help!
![image](https://user-images.githubusercontent.com/54981687/166090044-ed8e4cb1-9fcd-4a23-a3fc-1250dc2c134e.png)

**Comment by ladnir** [comment]
Use kkrt in libPSI

**Comment by cyy521xx** [comment]
I copied Kkrt from libPSI and make, and I got the following error.
![image](https://user-images.githubusercontent.com/54981687/166181253-e071540a-3b09-43e4-b0c2-6dad71ff6609.png)
![image](https://user-images.githubusercontent.com/54981687/166181294-b581d371-1c94-4718-8e63-d0fb6cd85a3e.png)
Looking forward to your reply, thanks!

**Comment by ladnir** [comment]
Delete bark oprf and just use libPSI. Look at the Readme.

**Comment by cyy521xx** [comment]
Thankfully, I will do so.
