### ISSUE TITLE
Having trouble with build.

### ISSUE THREAD

**Issue by danxinnoble** [osu-crypto/BaRK-OPRF#2]
Hi.

I'm trying to build BaRK-OPRF on a fresh Ubuntu install. Here are the commands I executed:
$ git clone https://github.com/osu-crypto/BaRK-OPRF
$ cd BaRK-OPRF/thirdparty/
$ bash all_linux.get
[Get sudo prompt. Enter user (admin)'s password.]
$ cd ..
$ make

I then get the following error:
g++ -ggdb -ffunction-sections -O3 -Wall -std=c++11 -maes -msse2 -msse4.1 -mpclmul -Wfatal-errors -pthread -Wno-narrowing  -I./bOPRFlib -I./thirdparty/linux -I./thirdparty/linux/boost/includes -I./thirdparty/linux/miracl -I./thirdparty/linux/mpir -I./thirdparty/linux/cryptopp -std=c++11  -DNDEBUG -DRELEASE -c bOPRFlib/Crypto/PRNG.cpp -o Release/./bOPRFlib/Crypto/PRNG.o -MD -MF Release/./bOPRFlib/Crypto/PRNG.dep
bOPRFlib/Crypto/PRNG.cpp: In member function ‘void bOPRF::PRNG::refillBuffer()’:
bOPRFlib/Crypto/PRNG.cpp:152:50: error: ‘_mm_cvtsi64_si128’ was not declared in this scope
    mIndexArray[i] = _mm_cvtsi64_si128(mBlockIdx++);
                                                  ^
compilation terminated due to -Wfatal-errors.
makefile:119: recipe for target 'Release/./bOPRFlib/Crypto/PRNG.o' failed
make: *** [Release/./bOPRFlib/Crypto/PRNG.o] Error 1

Any idea what is going wrong here? Or how I can fix it?

**Comment by ladnir** [comment]
Try adding 
```
#include <emmintrin.h>
```
to the to of `bOPRFlib/Crypto/PRNG.cpp`

If you are using this library as a submodule in a larger project, I would suggest using the [libOTe](https://github.com/osu-crypto/libOTe/tree/master/libOTe/NChooseOne/Kkrt) version instead. It has been optimized.

**Comment by ladnir** [comment]
Actually, that won't work, that #include is performed in defines.h... What version of g++ are you running?

**Comment by danxinnoble** [comment]
Output of: $ g++ --version
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.1) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.

**Comment by ladnir** [comment]
Not sure what the issue is. For some reason the `#include <emmintrin.h>` isn't making  [_mm_cvtsi64_si128](https://msdn.microsoft.com/en-us/library/bb514072%28v=vs.120%29.aspx?f=255&MSPPError=-2147217396) available. 

Are you on a 32bit system? This [person appears](https://github.com/p12tic/libsimdpp/issues/1) to have an issue in that case.

**Comment by danxinnoble** [comment]
Ah yes. It's 32-bit. 

Let me make a new vm with a 64-bit Ubuntu and see if that works.

**Comment by ladnir** [comment]
FYI, libOTe works on Windows, Mac, and Linux. You could just use that on you native system...

**Comment by danxinnoble** [comment]
Yep- when I ran it on 64-bit Ubuntu it worked.

Thanks for your help.
