### ISSUE TITLE
Running all_win.ps1 on Windows failed

### ISSUE THREAD

**Issue by haochenuw** [osu-crypto/BaRK-OPRF#5]
This is what I got. I suppose boost is messed up somehow but can't quite fix it. 
```
Exception calling "ExtractToDirectory" with "2" argument(s): "Could not find a part of the path 'C:\Users\haoche\Source
\Repos\BaRK-OPRF\thirdparty\win\boost_1_63_0\libs\geometry\doc\html\geometry\reference\spatial_indexes\boost__geometry_
_index__rtree\rtree_parameters_type_const____indexable_getter_const____value_equal_const____allocator_type_const___.htm
l'."
At C:\Users\haoche\Source\Repos\BaRK-OPRF\thirdparty\win\getBoost.ps1:34 char:5
+     [io.compression.zipfile]::ExtractToDirectory($destination, $PWD)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : DirectoryNotFoundException
```

**Comment by nitrieu** [comment]
Thanks Hao,

The [getBoost.ps1](https://github.com/osu-crypto/BaRK-OPRF/blob/master/thirdparty/win/getBoost.ps1#L46) works with VS 2015 only. If you are using VS 2017 or 2019, you can follow [this link](https://stackoverflow.com/questions/41464356/build-boost-with-msvc-14-1-vs2017-rc) to install it. 

Remember to add the [corresponding parameters](https://github.com/osu-crypto/BaRK-OPRF/blob/master/thirdparty/win/getBoost.ps1#L46) for b2. For example, if you use vs 2017, you will do `.\b2.exe  toolset=msvc-14.1 architecture=x86 address-model=64 --with-thread --with-filesystem --with-regex --with-date_time stage link=static variant=debug,release runtime-link=static threading=multi`
