### ISSUE TITLE
How to understand the output intersection?

### ISSUE THREAD

**Issue by fqliao** [osu-crypto/BaRK-OPRF#6]
Hello,

I set `senderSize = (1 << 3)` and `recverSize = (1 << 3)` , and run `BopTest()`, the output `recvPSIs.mIntersection` is `[6, 3]`, not the elements in `sendSet` and `recvSet`. What is the meaning of  `[6, 3]`, how to understand the output intersection?

**Comment by ladnir** [comment]
The output indexes the input sets. That is, the 6th and 3rd input items are in the intersection.

FYI, libPSI has an optimized version of the implementation.
