### ISSUE TITLE
batch processing

### ISSUE THREAD

**Issue by DaneilNo1** [osu-crypto/BaRK-OPRF#9]
Thanks for your open source code!
When I read this code, I found that there is a batch processing in the SSOTSender.cpp(SSOTReceiver.cpp). Instead of sending a message of m length, this code send BASE_OT_COUNT length for each batches. But the "mGens" is always same in each batches, which means that there will be a lot of identical outputs of the OPRF. Did I miss any details that make me got this false conclusion? Or it's some trick of achieving the fast implementation?

**Comment by ladnir** [comment]
Consider using the KKRT protocol is libPSI as a reference.
